--- #YAML:1.0
name:                Purple
version:             1.3
abstract:            Distributed granular addresses on the web
license:             ~
author:              
    - BlueOxen Associates <purple@blueoxen.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DB_File:                       0
    DBD::SQLite:                   0
    HTTP::Server::Simple:          0.18
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
