--- #YAML:1.0
name:               Purple
version:            1.1
abstract:           Distributed granular addresses on the web
author:
    - BlueOxen Associates <purple@blueoxen.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:          0
    HTTP::Server::Simple:  0.18
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
